import { NextResponse } from 'next/server';

// This file is kept for reference, but we're not using WebSockets directly.
// Instead, we're using the Deepgram client-side SDK with temporary tokens
// generated by the getDeepgramToken API route.

export async function GET() {
  return NextResponse.json(
    { 
      message: "WebSocket transcription has been replaced with client-side SDK using temporary tokens.",
      info: "Please use the /api/getDeepgramToken endpoint to get a temporary token for client-side use."
    },
    { status: 200 }
  );
}
